[package]
name = "fingerprint-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3"
zbus = "5.0"
tokio = { version = "1.41.0", features = ["full"] }

[[example]]
path = "./src/example.rs"
name = "example"